### ISSUE TITLE
make cannot find python2 interpreter

### ISSUE THREAD

**Issue by franciscsimon** [RedisLabsModules/readies#101]
running make from RedisGraph invoking the make command results in this error message on ubuntu 20.04 server
i checked the readies directory ... it seems to have the python2 interpreter ther but it is still not working and running `make setup` does not change anything because the make target is not available in the RedisGraph top Makefile

```GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Reading makefile 'Makefile'...
Reading makefile 'deps/readies/mk/main' (search path) (no ~ expansion)...
make[2]: Entering directory '/home/opunix/RedisGraph/deps/RediSearch'
deps/readies/mk/main:45: *** Cannot find python2 interpreter.
Use can install one by running 'make setup'..  Stop.
make[2]: Leaving directory '/home/opunix/RedisGraph/deps/RediSearch'
Reaping losing child 0x55b80ad5b040 PID 50124
make[1]: *** [Makefile:241: /home/opunix/RedisGraph/bin/linux-x64-release/search-static/libredisearch.a] Error 2
Removing child 0x55b80ad5b040 PID 50124 from chain.
make[1]: Leaving directory '/home/opunix/RedisGraph/src'
Reaping losing child 0x55870f2b4360 PID 50108
make: *** [Makefile:26: all] Error 2
Removing child 0x55870f2b4360 PID 50108 from chain.```

**Comment by franciscsimon** [comment]
Hey @rafie thx for the reply, it seems to build now the redis-graph library but unfortunately after running the commands you proposed i still get this error:
````[100%] Linking C static library libgraphblas.a
make[6]: Leaving directory '/root/redis-graph-2.8.8/deps/GraphBLAS/build'
[100%] Built target graphblas_static
make[5]: Leaving directory '/root/redis-graph-2.8.8/deps/GraphBLAS/build'
make[4]: Leaving directory '/root/redis-graph-2.8.8/deps/GraphBLAS/build'
make[3]: Leaving directory '/root/redis-graph-2.8.8/deps/GraphBLAS/build'
make[2]: Leaving directory '/root/redis-graph-2.8.8/deps/GraphBLAS'
make -C /root/redis-graph-2.8.8/deps/RediSearch STATIC=1 BINROOT=/root/redis-graph-2.8.8/bin/linux-x64-release
make[2]: Entering directory '/root/redis-graph-2.8.8/deps/RediSearch'
deps/readies/mk/main:45: *** Cannot find python2 interpreter.
Use can install one by running 'make setup'..  Stop.
make[2]: Leaving directory '/root/redis-graph-2.8.8/deps/RediSearch'
make[1]: *** [Makefile:241: /root/redis-graph-2.8.8/bin/linux-x64-release/search-static/libredisearch.a] Error 2
make[1]: Leaving directory '/root/redis-graph-2.8.8/src'
make: *** [Makefile:26: all] Error 2
```

**Comment by domrod** [comment]
I had the same problem but as the error message says you need `python2`, not python3.

I solved it with
```bash
./deps/readies/bin/getpy2
```
and then
```bash
make
```

**Comment by rafie** [comment]
Hello @domrod,
Please note that it is more effective to discuss RedisGraph-specific issues in the RedisGraph repo.
As for the setup/build process (assuming master), the right procedure at the moment is:
```
./deps/readies/bin/getpy3
./deps/readies/bin/getpy2
./sbin/system-setup.py
make
```

Please note that RedisGraph's automation Python version is 3, but a dependent RediSearch submodule unfortunately still requires Python 2.
This will be removed very soon, so we'll be Python 3 everywhere.

**Comment by viploveb** [comment]
> Hello @domrod, Please note that it is more effective to discuss RedisGraph-specific issues in the RedisGraph repo. As for the setup/build process (assuming master), the right procedure at the moment is:
> 
> ```
> ./deps/readies/bin/getpy3
> ./deps/readies/bin/getpy2
> ./sbin/system-setup.py
> make
> ```
> 
> Please note that RedisGraph's automation Python version is 3, but a dependent RediSearch submodule unfortunately still requires Python 2. This will be removed very soon, so we'll be Python 3 everywhere.

These commands should be mentioned in the redisgraph docs though

**Comment by XChikuX** [comment]
Where are we on full python3 migration?
python2 has been decprecated since ages. I've had to manually install it on newer systems like Ubuntu 22.04 and it is not elegant.
